name: Deploy to Railway (Staging)

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Railway CLI
        uses: railwayapp/cli-action@v1

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service main-app